### ISSUE TITLE
CSV Import Doesn't Respect NULLs

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#1006] opened 2024-08-23 20:39 UTC
Reviewing [this RME project](https://data.riverscapes.net/p/0aa68c32-c599-4d84-980c-0dcce378d252/) I noticed that in the `metrics` database table there are some values that should be `NULL`. DataGrip makes this clear to see.

<img width="755" alt="Screenshot 2024-08-23 at 1 28 39 PM" src="https://github.com/user-attachments/assets/d2589cd9-0754-4c04-85ee-18daae026eb3">

These data are imported from [this CSV](https://github.com/Riverscapes/riverscapes-tools/blob/dev/packages/rme/rme/database/data_metrics/metrics.csv):

```csv
metric_id,name,machine_code,data_type,field_name,description,small,medium,large,method,metric_group_id,is_active,docs_url
1,Ownership,AGENCY,TEXT,rme_dgo_ownership,,200,400,1400,,3,1,
2,State,STATE,TEXT,rme_dgo_state,,200,400,1400,,3,1,
3,County,COUNTY,TEXT,rme_dgo_county,,200,400,1400,,3,1,
4,Primary Channel Gradient,STRMGRAD,REAL,RME_IGO_prim_channel_gradient,Change in elevation along Flowline length,200,400,1400,(𝑡𝑜𝑝 𝑜𝑓 𝑟𝑒𝑎𝑐ℎ 𝑒𝑙𝑒𝑣𝑎𝑡𝑖𝑜𝑛 −𝑏𝑜𝑡𝑡𝑜𝑚 𝑜𝑓 𝑟𝑒𝑎𝑐ℎ 𝑒𝑙𝑒𝑣𝑎𝑡𝑖𝑜𝑛)/(𝑛𝑒𝑡𝑤𝑜𝑟𝑘 𝑙𝑒𝑛𝑔𝑡ℎ),1,1,"Hack, J. T. (1973). Stream-profile analysis and stream-gradient index. Journal of Research of the U.S. Geological Survey, 1(4), 421–429. Nagel, D., Buffington, J., & Isaak, D. (4006). Comparison of methods for estimating stream channel gradient using GIS. USDA Forest Service, Rocky Mountain Research Station Boise Aquatic Sciences Lab."
5,Valley Gradient,VALGRAD,REAL,RME_IGO_valleybottom_gradient,Change in elevation along Centerline length,200,400,1400,(𝑡𝑜𝑝 𝑜𝑓 𝑠𝑒𝑔𝑚𝑒𝑛𝑡 𝑒𝑙𝑒𝑣. −𝑏𝑜𝑡𝑡𝑜𝑚 𝑜𝑓 𝑠𝑒𝑔𝑚𝑒𝑛𝑡 𝑒𝑙𝑒𝑣.)/(𝑣𝑎𝑙𝑙𝑒𝑦 𝑏𝑜𝑡𝑡𝑜𝑚 𝑐𝑒𝑛𝑡𝑒𝑟𝑙𝑖𝑛𝑒),1,1,
6,Relative Flow Length,RELFLWLNGTH,REAL,RME_IGO_rel_flow_length,,200,400,1400,sum of all blue line lenth/valley length,1,1,
7,Valley Azimuth,VALAZMTH,REAL,RME_IGO_valley_azimuth,,200,400,1400,,,0,
8,Confluence Count,CONF,INTEGER,RME_DGO_confluences,,200,400,1400,,2,1,
9,Diffluence Count,DIFF,INTEGER,RME_DGO_diffluences,,200,400,1400,,2,1,
10,Tributary Junction Count,TRIBS,REAL,RME_IGO_trib_per_km,,400,400,1400,,2,1,
```

I don't understand why some missing values are correctly being set to NULL while others are not. Probably an easy fix to check for either empty string or `None`. 

Note that I believe the code that imports the CSV is used by several of our models. Definitely BRAT as well.

**Comment by r-k-g** [comment] 2024-08-28 21:31
Fixed with commit https://github.com/Riverscapes/riverscapes-tools/commit/b94c53ee41032625fc10830cd071b51d2d8033cb.

With the schema fix, there are no NULL values in this column. This is expected behaviour because that column is present in the CSV, just with no content. NULL would be indicative of a missing column or other issue.

**Closed** 2024-08-28 23:53 UTC
Labels: :bug: bug, pkg:RME
