### ISSUE TITLE
Brat project did not validate (cybercastor)

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#480] opened 2021-11-17 18:46 UTC
```
2021-11-17 12:13:16:: [info] [BRAT Build] BRAT build completed successfully.
2021-11-17 12:13:18:: RSCLI: v1.2.5
2021-11-17 12:13:18:: Success reading config file: /root/.riverscapes
2021-11-17 12:13:23:: Setting program: BLM (BLM)
2021-11-17 12:13:23:: initialization done
2021-11-17 12:13:24:: Authenticating without input
2021-11-17 12:13:25:: Logged in successfully
2021-11-17 12:13:25:: [BLM Montana and Dakotas] RSCli Upload: Wed Nov 17 2021 12:13:25 GMT+0000 (Coordinated Universal Time)
2021-11-17 12:13:25:: ------------------------------------------------------------------------------------------------------
2021-11-17 12:13:25:: apiCall Error {
2021-11-17 12:13:25::   url: 'https://gco5qebdt4.execute-api.us-west-2.amazonaws.com/production/api',
2021-11-17 12:13:25::   jwt: 'eyJraWQiOiJJc2xMaXFKdkVPT2c2VDZucFgxbDBLQW5NUGhTT1ZpVDB3Y0RENFpvWXhnPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIyMWM0ZGY1Ni05MzY1LTRiZjItOTEwYS00MWM5ZGVkYWYzNWMiLCJjb2duaXRvOmdyb3VwcyI6WyJBZG1pbiJdLCJldmVudF9pZCI6IjNiYmJkMzkzLThlMWEtNDA3Zi1hMDk5LTUzZDIzMGYyMTQxZCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2MzcxNTEyMDUsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy13ZXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtd2VzdC0yX2prSzhIUlhCVSIsImV4cCI6MTYzNzE1NDgwNSwiaWF0IjoxNjM3MTUxMjA1LCJqdGkiOiJhY2QwY2FhMS1jYTUyLTRhYTQtOGJkYS1hYjBlM2VhMGNjOWMiLCJjbGllbnRfaWQiOiIybjFmanNrZjIxaGd1dWg1bHFjb3ZzMTM1NCIsInVzZXJuYW1lIjoiMjFjNGRmNTYtOTM2NS00YmYyLTkxMGEtNDFjOWRlZGFmMzVjIn0.SS1pKTiYocadk_qj8bS2c_12EfD88b9ESfJZo5uVR7mfxkZoKE-Vn7grY7_fMXUMAhkZdnkw18wbj890Rumb62qBZ131yyrs0tPh0zb6ep7cN8Gpy1mlBFoxL1qF7VnPSDtlV6uVQ1_B2QBWDnBgJhhqBAjqUSygOerUJRKya-h3gDdafHma_SIfaCB721rfPdvnfI613JMmMadZWof2hYzAiaXWIZ5DQqo2Th5yxJmevihoSy2mKy2TQzXQxi7u5lQTTcDx_ZLFjmoHzLwSEZltlFbK8bbkwzXplEOO-NuPXQPuJKgRujJ5TVRFWNz7c_2BoaRvtWeejfIZBXBS1w',
2021-11-17 12:13:25::   query: 'query validateProject($xml: String!, $projType: String!, $program: String!) {\n' +
2021-11-17 12:13:25::     '  validate(xml: $xml, projType: $projType, program: $program) {\n' +
2021-11-17 12:13:25::     '    result\n' +
2021-11-17 12:13:25::     '    xmlErrors\n' +
2021-11-17 12:13:25::     '  }\n' +
2021-11-17 12:13:25::     '}\n',
2021-11-17 12:13:25::   variables: {
2021-11-17 12:13:25::     xml: '<?xml version="1.0" ?>\n' +
2021-11-17 12:13:25::       '<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xml.riverscapes.xyz/Projects/XSD/V1/BRAT.xsd">\n' +
2021-11-17 12:13:25::       '\t<Name>BRAT for HUC 10040202</Name>\n' +
2021-11-17 12:13:25::       '\t<ProjectType>BRAT</ProjectType>\n' +
2021-11-17 12:13:25::       '\t<MetaData>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="ModelVersion">4.3.2</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="dateCreated" type="isodate">2021-11-16T17:28:13.730993</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="HUC8">10040202</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="HUC">10040202</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="BRATBuildVersion">4.3.2</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="BRATBuildTimestamp">1637083693</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="Runner">Cybercastor</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="BRAT_Build_DateTime">2021-11-16T17:29:32.619361</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="Streamside_Buffer">30.0</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="Riparian_Buffer">100.0</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="Reach_Codes">33400,33600,33601,33603,46000,46003,46006,46007,55800</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="Canal_Codes">33600,33601,33603</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="Max_Waterbody">0.001</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="Elevation_Buffer">100.0</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="gdal_srs_proj4">+proj=longlat +datum=WGS84 +no_defs</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="gdal_srs_axis_mapping_strategy">0</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="Watershed">Middle Musselshell</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="BratBuildProcTimeS" type="int">67502.94</Meta>\n' +
2021-11-17 12:13:25::       '\t\t<Meta name="BratBuildProcTimeHuman">18:45 hours</Meta>\n' +
2021-11-17 12:13:25::       '\t</MetaData>\n' +
2021-11-17 12:13:25::       '\t<Realizations>\n' +
2021-11-17 12:13:25::       '\t\t<BRAT id="BRAT" dateCreated="2021-11-16T17:28:13.734714" guid="2be41d2a-e710-411d-993a-c0337ff7ea84" productVersion="4.3.2">\n' +
2021-11-17 12:13:25::       '\t\t\t<Name>BRAT for HUC 10040202</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t<LogFile guid="b43c5ca1-09fa-44d5-a140-6392ed9270db" id="LOGFILE">\n' +
2021-11-17 12:13:25::       '\t\t\t\t<Name>Log</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t\t<Path>brat_build.log</Path>\n' +
2021-11-17 12:13:25::       '\t\t\t</LogFile>\n' +
2021-11-17 12:13:25::       '\t\t\t<Inputs>\n' +
2021-11-17 12:13:25::       '\t\t\t\t<DEM guid="385b688a-8a5d-4723-bcf1-2aa91947e403" id="DEM">\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t<Name>NED 10m DEM</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t<Path>inputs/dem.tif</Path>\n' +
2021-11-17 12:13:25::       '\t\t\t\t</DEM>\n' +
2021-11-17 12:13:25::       '\t\t\t\t<Raster guid="35a9fa55-398a-4fb8-89b3-7f8e04842343" id="EXVEG">\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t<Name>Existing Vegetation</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t<Path>inputs/existing_veg.tif</Path>\n' +
2021-11-17 12:13:25::       '\t\t\t\t</Raster>\n' +
2021-11-17 12:13:25::       '\t\t\t\t<Raster guid="9876e9e1-00a1-4864-afa0-0351efa37a61" id="HISTVEG">\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t<Name>Historic Vegetation</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t<Path>inputs/historic_veg.tif</Path>\n' +
2021-11-17 12:13:25::       '\t\t\t\t</Raster>\n' +
2021-11-17 12:13:25::       '\t\t\t\t<Raster guid="1ac41b52-0d6e-4661-982b-9731f8de1b78" id="HILLSHADE">\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t<Name>DEM Hillshade</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t<Path>inputs/dem_hillshade.tif</Path>\n' +
2021-11-17 12:13:25::       '\t\t\t\t</Raster>\n' +
2021-11-17 12:13:25::       '\t\t\t\t<Raster guid="7191861b-f987-4301-8959-e6f0ec6dacd7" id="SLOPE">\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t<Name>Slope Raster</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t<Path>inputs/slope.tif</Path>\n' +
2021-11-17 12:13:25::       '\t\t\t\t</Raster>\n' +
2021-11-17 12:13:25::       '\t\t\t\t<Geopackage guid="dd11bec4-ddfc-4002-9a4b-76476ea12d77" id="INPUTS">\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t<Name>Confinement</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t<Path>inputs/inputs.gpkg</Path>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t<Layers>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t<Vector guid="82ea9c46-abd5-49e4-9da7-f6e146d2a927" id="FLOWLINES">\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Name>Segmented Flowlines</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Path>flowlines</Path>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t</Vector>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t<Vector guid="49bea238-9d29-4be2-ba89-79b62e93db2f" id="FLOW_AREA">\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Name>NHD Flow Area</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Path>flowareas</Path>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t</Vector>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t<Vector guid="4d963004-c56c-4977-9ec1-417a5223748c" id="WATERBODIES">\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Name>NHD Waterbody</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Path>waterbodies</Path>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t</Vector>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t<Vector guid="4597d102-1314-4e08-9f9b-7c7e59e6283f" id="VALLEY_BOTTOM">\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Name>Valley Bottom</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Path>valley_bottom</Path>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t</Vector>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t<Vector guid="15b8a321-e595-4235-b292-1569dac254d4" id="ROADS">\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Name>Roads</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Path>roads</Path>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t</Vector>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t<Vector guid="7a4ee04a-c3a5-4050-9d29-84055484f5a5" id="RAIL">\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Name>Rail</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Path>rail</Path>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t</Vector>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t<Vector guid="773225fd-2d43-4052-a5e8-426afa4da964" id="CANALS">\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Name>Canals</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Path>canals</Path>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t</Vector>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t</Layers>\n' +
2021-11-17 12:13:25::       '\t\t\t\t</Geopackage>\n' +
2021-11-17 12:13:25::       '\t\t\t</Inputs>\n' +
2021-11-17 12:13:25::       '\t\t\t<Intermediates/>\n' +
2021-11-17 12:13:25::       '\t\t\t<Outputs>\n' +
2021-11-17 12:13:25::       '\t\t\t\t<Geopackage guid="305937d5-9c6c-4d61-b28f-5bf1101094c5" id="OUTPUTS">\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t<Name>BRAT</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t<Path>outputs/brat.gpkg</Path>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t<Layers>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t<Vector guid="dc2376b8-9d00-41c4-9826-d3cdd6d4f879" id="BRAT_GEOMETRY">\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Name>BRAT Geometry</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Path>ReachGeometry</Path>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t</Vector>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t<Vector guid="407e5b75-7362-4709-b532-86a1db32402d" id="BRAT_RESULTS">\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Name>BRAT</Name>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t\t<Path>vwReaches</Path>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t\t</Vector>\n' +
2021-11-17 12:13:25::       '\t\t\t\t\t</Layers>\n' +
2021-11-17 12:13:25::       '\t\t\t\t</Geopackage>\n' +
2021-11-17 12:13:25::       '\t\t\t</Outputs>\n' +
2021-11-17 12:13:25::       '\t\t</BRAT>\n' +
2021-11-17 12:13:25::       '\t</Realizations>\n' +
2021-11-17 12:13:25::       '</Project>\n',
2021-11-17 12:13:25::     program: 'BLM',
2021-11-17 12:13:25::     projType: 'BRAT'
2021-11-17 12:13:25::   },
2021-11-17 12:13:25::   err: Error: read ECONNRESET
2021-11-17 12:13:25::       at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
2021-11-17 12:13:25::     errno: -104,
2021-11-17 12:13:25::     code: 'ECONNRESET',
2021-11-17 12:13:25::     syscall: 'read',
2021-11-17 12:13:25::     config: {
2021-11-17 12:13:25::       url: 'https://gco5qebdt4.execute-api.us-west-2.amazonaws.com/production/api',
2021-11-17 12:13:25::       method: 'post',
2021-11-17 12:13:25::       data: '{"query":"query validateProject($xml: String!, $projType: String!, $program: String!) {\\n  validate(xml: $xml, projType: $projType, program: $program) {\\n    result\\n    xmlErrors\\n  }\\n}\\n","variables":{"xml":"<?xml version=\\"1.0\\" ?>\\n<Project xmlns:xsi=\\"http://www.w3.org/2001/XMLSchema-instance\\" xsi:noNamespaceSchemaLocation=\\"http://xml.riverscapes.xyz/Projects/XSD/V1/BRAT.xsd\\">\\n\\t<Name>BRAT for HUC 10040202</Name>\\n\\t<ProjectType>BRAT</ProjectType>\\n\\t<MetaData>\\n\\t\\t<Meta name=\\"ModelVersion\\">4.3.2</Meta>\\n\\t\\t<Meta name=\\"dateCreated\\" type=\\"isodate\\">2021-11-16T17:28:13.730993</Meta>\\n\\t\\t<Meta name=\\"HUC8\\">10040202</Meta>\\n\\t\\t<Meta name=\\"HUC\\">10040202</Meta>\\n\\t\\t<Meta name=\\"BRATBuildVersion\\">4.3.2</Meta>\\n\\t\\t<Meta name=\\"BRATBuildTimestamp\\">1637083693</Meta>\\n\\t\\t<Meta name=\\"Runner\\">Cybercastor</Meta>\\n\\t\\t<Meta name=\\"BRAT_Build_DateTime\\">2021-11-16T17:29:32.619361</Meta>\\n\\t\\t<Meta name=\\"Streamside_Buffer\\">30.0</Meta>\\n\\t\\t<Meta name=\\"Riparian_Buffer\\">100.0</Meta>\\n\\t\\t<Meta name=\\"Reach_Codes\\">33400,33600,33601,33603,46000,46003,46006,46007,55800</Meta>\\n\\t\\t<Meta name=\\"Canal_Codes\\">33600,33601,33603</Meta>\\n\\t\\t<Meta name=\\"Max_Waterbody\\">0.001</Meta>\\n\\t\\t<Meta name=\\"Elevation_Buffer\\">100.0</Meta>\\n\\t\\t<Meta name=\\"gdal_srs_proj4\\">+proj=longlat +datum=WGS84 +no_defs</Meta>\\n\\t\\t<Meta name=\\"gdal_srs_axis_mapping_strategy\\">0</Meta>\\n\\t\\t<Meta name=\\"Watershed\\">Middle Musselshell</Meta>\\n\\t\\t<Meta name=\\"BratBuildProcTimeS\\" type=\\"int\\">67502.94</Meta>\\n\\t\\t<Meta name=\\"BratBuildProcTimeHuman\\">18:45 hours</Meta>\\n\\t</MetaData>\\n\\t<Realizations>\\n\\t\\t<BRAT id=\\"BRAT\\" dateCreated=\\"2021-11-16T17:28:13.734714\\" guid=\\"2be41d2a-e710-411d-993a-c0337ff7ea84\\" productVersion=\\"4.3.2\\">\\n\\t\\t\\t<Name>BRAT for HUC 10040202</Name>\\n\\t\\t\\t<LogFile guid=\\"b43c5ca1-09fa-44d5-a140-6392ed9270db\\" id=\\"LOGFILE\\">\\n\\t\\t\\t\\t<Name>Log</Name>\\n\\t\\t\\t\\t<Path>brat_build.log</Path>\\n\\t\\t\\t</LogFile>\\n\\t\\t\\t<Inputs>\\n\\t\\t\\t\\t<DEM guid=\\"385b688a-8a5d-4723-bcf1-2aa91947e403\\" id=\\"DEM\\">\\n\\t\\t\\t\\t\\t<Name>NED 10m DEM</Name>\\n\\t\\t\\t\\t\\t<Path>inputs/dem.tif</Path>\\n\\t\\t\\t\\t</DEM>\\n\\t\\t\\t\\t<Raster guid=\\"35a9fa55-398a-4fb8-89b3-7f8e04842343\\" id=\\"EXVEG\\">\\n\\t\\t\\t\\t\\t<Name>Existing Vegetation</Name>\\n\\t\\t\\t\\t\\t<Path>inputs/existing_veg.tif</Path>\\n\\t\\t\\t\\t</Raster>\\n\\t\\t\\t\\t<Raster guid=\\"9876e9e1-00a1-4864-afa0-0351efa37a61\\" id=\\"HISTVEG\\">\\n\\t\\t\\t\\t\\t<Name>Historic Vegetation</Name>\\n\\t\\t\\t\\t\\t<Path>inputs/historic_veg.tif</Path>\\n\\t\\t\\t\\t</Raster>\\n\\t\\t\\t\\t<Raster guid=\\"1ac41b52-0d6e-4661-982b-9731f8de1b78\\" id=\\"HILLSHADE\\">\\n\\t\\t\\t\\t\\t<Name>DEM Hillshade</Name>\\n\\t\\t\\t\\t\\t<Path>inputs/dem_hillshade.tif</Path>\\n\\t\\t\\t\\t</Raster>\\n\\t\\t\\t\\t<Raster guid=\\"7191861b-f987-4301-8959-e6f0ec6dacd7\\" id=\\"SLOPE\\">\\n\\t\\t\\t\\t\\t<Name>Slope Raster</Name>\\n\\t\\t\\t\\t\\t<Path>inputs/slope.tif</Path>\\n\\t\\t\\t\\t</Raster>\\n\\t\\t\\t\\t<Geopackage guid=\\"dd11bec4-ddfc-4002-9a4b-76476ea12d77\\" id=\\"INPUTS\\">\\n\\t\\t\\t\\t\\t<Name>Confinement</Name>\\n\\t\\t\\t\\t\\t<Path>inputs/inputs.gpkg</Path>\\n\\t\\t\\t\\t\\t<Layers>\\n\\t\\t\\t\\t\\t\\t<Vector guid=\\"82ea9c46-abd5-49e4-9da7-f6e146d2a927\\" id=\\"FLOWLINES\\">\\n\\t\\t\\t\\t\\t\\t\\t<Name>Segmented Flowlines</Name>\\n\\t\\t\\t\\t\\t\\t\\t<Path>flowlines</Path>\\n\\t\\t\\t\\t\\t\\t</Vector>\\n\\t\\t\\t\\t\\t\\t<Vector guid=\\"49bea238-9d29-4be2-ba89-79b62e93db2f\\" id=\\"FLOW_AREA\\">\\n\\t\\t\\t\\t\\t\\t\\t<Name>NHD Flow Area</Name>\\n\\t\\t\\t\\t\\t\\t\\t<Path>flowareas</Path>\\n\\t\\t\\t\\t\\t\\t</Vector>\\n\\t\\t\\t\\t\\t\\t<Vector guid=\\"4d963004-c56c-4977-9ec1-417a5223748c\\" id=\\"WATERBODIES\\">\\n\\t\\t\\t\\t\\t\\t\\t<Name>NHD Waterbody</Name>\\n\\t\\t\\t\\t\\t\\t\\t<Path>waterbodies</Path>\\n\\t\\t\\t\\t\\t\\t</Vector>\\n\\t\\t\\t\\t\\t\\t<Vector guid=\\"4597d102-1314-4e08-9f9b-7c7e59e6283f\\" id=\\"VALLEY_BOTTOM\\">\\n\\t\\t\\t\\t\\t\\t\\t<Name>Valley Bottom</Name>\\n\\t\\t\\t\\t\\t\\t\\t<Path>valley_bottom</Path>\\n\\t\\t\\t\\t\\t\\t</Vector>\\n\\t\\t\\t\\t\\t\\t<Vector guid=\\"15b8a321-e595-4235-b292-1569dac254d4\\" id=\\"ROADS\\">\\n\\t\\t\\t\\t\\t\\t\\t<Name>Roads</Name>\\n\\t\\t\\t\\t\\t\\t\\t<Path>roads</Path>\\n\\t\\t\\t\\t\\t\\t</Vector>\\n\\t\\t\\t\\t\\t\\t<Vector guid=\\"7a4ee04a-c3a5-4050-9d29-84055484f5a5\\" id=\\"RAIL\\">\\n\\t\\t\\t\\t\\t\\t\\t<Name>Rail</Name>\\n\\t\\t\\t\\t\\t\\t\\t<Path>rail</Path>\\n\\t\\t\\t\\t\\t\\t</Vector>\\n\\t\\t\\t\\t\\t\\t<Vector guid=\\"773225fd-2d43-4052-a5e8-426afa4da964\\" id=\\"CANALS\\">\\n\\t\\t\\t\\t\\t\\t\\t<Name>Canals</Name>\\n\\t\\t\\t\\t\\t\\t\\t<Path>canals</Path>\\n\\t\\t\\t\\t\\t\\t</Vector>\\n\\t\\t\\t\\t\\t</Layers>\\n\\t\\t\\t\\t</Geopackage>\\n\\t\\t\\t</Inputs>\\n\\t\\t\\t<Intermediates/>\\n\\t\\t\\t<Outputs>\\n\\t\\t\\t\\t<Geopackage guid=\\"305937d5-9c6c-4d61-b28f-5bf1101094c5\\" id=\\"OUTPUTS\\">\\n\\t\\t\\t\\t\\t<Name>BRAT</Name>\\n\\t\\t\\t\\t\\t<Path>outputs/brat.gpkg</Path>\\n\\t\\t\\t\\t\\t<Layers>\\n\\t\\t\\t\\t\\t\\t<Vector guid=\\"dc2376b8-9d00-41c4-9826-d3cdd6d4f879\\" id=\\"BRAT_GEOMETRY\\">\\n\\t\\t\\t\\t\\t\\t\\t<Name>BRAT Geometry</Name>\\n\\t\\t\\t\\t\\t\\t\\t<Path>ReachGeometry</Path>\\n\\t\\t\\t\\t\\t\\t</Vector>\\n\\t\\t\\t\\t\\t\\t<Vector guid=\\"407e5b75-7362-4709-b532-86a1db32402d\\" id=\\"BRAT_RESULTS\\">\\n\\t\\t\\t\\t\\t\\t\\t<Name>BRAT</Name>\\n\\t\\t\\t\\t\\t\\t\\t<Path>vwReaches</Path>\\n\\t\\t\\t\\t\\t\\t</Vector>\\n\\t\\t\\t\\t\\t</Layers>\\n\\t\\t\\t\\t</Geopackage>\\n\\t\\t\\t</Outputs>\\n\\t\\t</BRAT>\\n\\t</Realizations>\\n</Project>\\n","program":"BLM","projType":"BRAT"}}',
2021-11-17 12:13:25::       headers: [Object],
2021-11-17 12:13:25::       transformRequest: [Array],
2021-11-17 12:13:25::       transformResponse: [Array],
2021-11-17 12:13:25::       timeout: 0,
2021-11-17 12:13:25::       adapter: [Function: httpAdapter],
2021-11-17 12:13:25::       xsrfCookieName: 'XSRF-TOKEN',
2021-11-17 12:13:25::       xsrfHeaderName: 'X-XSRF-TOKEN',
2021-11-17 12:13:25::       maxContentLength: -1,
2021-11-17 12:13:25::       maxBodyLength: -1,
2021-11-17 12:13:25::       validateStatus: [Function: validateStatus],
2021-11-17 12:13:25::       transitional: [Object]
2021-11-17 12:13:25::     },
2021-11-17 12:13:25::     request: Writable {
2021-11-17 12:13:25::       _writableState: [WritableState],
2021-11-17 12:13:25::       _events: [Object: null prototype],
2021-11-17 12:13:25::       _eventsCount: 2,
2021-11-17 12:13:25::       _maxListeners: undefined,
2021-11-17 12:13:25::       _options: [Object],
2021-11-17 12:13:25::       _ended: true,
2021-11-17 12:13:25::       _ending: true,
2021-11-17 12:13:25::       _redirectCount: 0,
2021-11-17 12:13:25::       _redirects: [],
2021-11-17 12:13:25::       _requestBodyLength: 5138,
2021-11-17 12:13:25::       _requestBodyBuffers: [Array],
2021-11-17 12:13:25::       _onNativeResponse: [Function (anonymous)],
2021-11-17 12:13:25::       _currentRequest: [ClientRequest],
2021-11-17 12:13:25::       _currentUrl: 'https://gco5qebdt4.execute-api.us-west-2.amazonaws.com/production/api',
2021-11-17 12:13:25::       [Symbol(kCapture)]: false
2021-11-17 12:13:25::     },
2021-11-17 12:13:25::     response: undefined,
2021-11-17 12:13:25::     isAxiosError: true,
2021-11-17 12:13:25::     toJSON: [Function: toJSON]
2021-11-17 12:13:25::   }
2021-11-17 12:13:25:: }
2021-11-17 12:13:25:: read ECONNRESET
2021-11-17 12:13:25:: Project must validate against: https://xml.riverscapes.xyz/Projects/XSD/V1/<PROJTYPE>.xsd
2021-11-17 12:13:25::  ERROR read ECONNRESET
2021-11-17 12:13:25:: Error: Project file did not validate
2021-11-17 12:13:25:: <<BRAT PROCESS ENDED WITH AN ERROR>>\n\n
```
Huc: 10040202
[FAILED-10040202.log](https://github.com/Riverscapes/riverscapes-tools/files/7557186/FAILED-10040202.log)

**Comment by MattReimer** [comment] 2021-11-17 19:31
There's some evidence this seems to have been caused by a momentary network outage trying to reach the validation xsd.

Try rerunning

**Comment by MattReimer** [comment] 2021-12-13 17:39
@KellyMWhitehead can you close this if it's not an issue anymore

**Closed** 2021-12-13 18:34 UTC
Labels: :bug: bug, pkg:BRAT
