### ISSUE TITLE
BRAT Build failing on "CHK_Reaches_LengthKm"

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#810] opened 2023-07-18 22:44 UTC
Several Brat huc10's are failing due to this check in the database:
```
2023-07-18 17:15:15:: [error] [BRAT Build] CHECK constraint failed: CHK_Reaches_LengthKm
2023-07-18 17:15:15:: Traceback (most recent call last):
2023-07-18 17:15:15::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 334, in main
2023-07-18 17:15:15::     brat_build(
2023-07-18 17:15:15::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 202, in brat_build
2023-07-18 17:15:15::     reach_geometry(reach_geometry_path, dem_raster_path, elevation_buffer)
2023-07-18 17:15:15::   File "/usr/local/src/riverscapes-tools/lib/commons/rscommons/reach_geometry.py", line 93, in reach_geometry
2023-07-18 17:15:15::     write_db_attributes(os.path.dirname(flow_lines), reaches, [field_names['Length'], field_names['MaxElevation'], field_names['MinElevation'], field_names['Gradient']])
2023-07-18 17:15:15::   File "/usr/local/src/riverscapes-tools/lib/commons/rscommons/database.py", line 265, in write_db_attributes
2023-07-18 17:15:15::     curs.executemany(sql, results)
2023-07-18 17:15:15:: sqlite3.IntegrityError: CHECK constraint failed: CHK_Reaches_LengthKm
2023-07-18 17:15:16:: <<BRAT PROCESS ENDED WITH AN ERROR>>\n\n
```
[FAILED-1005000409.log](https://github.com/Riverscapes/riverscapes-tools/files/12089470/FAILED-1005000409.log)

I can provide more examples if needed.

**Comment by jtgilbert** [comment] 2023-07-19 00:23
I was having this issue with the San Luis Valley runs. There, it was an issue where some NHD features either had no length or were miniscule.

**Comment by jtgilbert** [comment] 2023-07-20 16:35
Update: This is a result of bad geometries from segmenting flowlines with the ownership layer. 
I'm implementing a fix with BRAT where it doesn't copy flowline features below a miniscule minimum length, but also repairing the ownership layer so that future RSContext reruns don't create this issue.

**Comment by philipbaileynar** [comment] 2023-07-25 22:55
Any progress on this Jordan?

**Comment by jtgilbert** [comment] 2023-07-26 14:49
yeah, the fix within BRAT is working, but of course doesn't address the cause (which is the ownership layer in RSContext).

**Comment by philipbaileynar** [comment] 2023-07-26 15:15
@KellyMWhitehead can you make sure that this fix is on the main branch and then queue the failed sqlBRAT runs please?

**Comment by jtgilbert** [comment] 2023-07-26 15:37
@KellyMWhitehead I'll do a PR and let you know when it's good to go.

**Comment by jtgilbert** [comment] 2023-07-26 17:38
@KellyMWhitehead fixes are merged onto dev

**Closed** 2023-07-31 15:20 UTC
Labels: :bug: bug, pkg:BRAT
