### ISSUE TITLE
Valley-bottom centerline

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#270] opened 2021-04-07 17:42 UTC
We need to enhance VBET to produce a valley centerline. This will be used for chopping the valley bottom into sausages, and also for metrics in the reach typing work.

Ideas....

1. Start by producing an intermediate dataset of all the input and output points.
    2. Don't mind if you do this via NetworkX or the NHD from/to node information.
    3. Make sure you filter the network down to just the FCodes used for VBET.
    4. Be aware of there potentially being multiple disconnected networks (i.e. multiple outflow places). Maybe we have a parameter that says each network much have at least 10 or 100 reaches etc before we bother generating a centerline.
5. Generate a centerline from each starting point to its corresponding outflow point.
6. The centerlines should merge and overlap at confluences. We need to remove duplicate line segments. The old code Matt wrote dealt with this issue.

Given that our VBET polygons are still flooding too much of the valley, perhaps this method should be developed standalone on a "clean" and "reliable" VBET generated by USU.

Here's the [open source code for generating centerlines](https://github.com/RBTDevelopmentGroup/rivertools).

**Comment by joewheaton** [comment] 2021-09-05 22:35
So this is a duplicate of #270, but a great alternative strategy that @philipbaileynar suggests, but we never got around to trying. 

- [ ] @KellyMWhitehead can you comment on whether you tried using the [RiverTools Centerline](https://github.com/RBTDevelopmentGroup/rivertools#centerline) or not?  
- [ ] @philipbaileynar it looks like it requires a thalweg as an input to work. Is this mainly to get over knowing what is upstream and downstream? If so, would your thalweg algorithm work maybe combined with suggestions in #382 about Euclidian distance from non-valley bottom cells to find a least cost path?

**Comment by philipbaileynar** [comment] 2021-09-10 04:50
This ticket is old. Deassigning Kelly until we have a coherent strategy to move forward.

- Kelly recently tried centerlines with the new jagged VBET and the tool just crashed because of the vast number of vertices.
- See my response to #414

**Comment by KellyMWhitehead** [comment] 2022-10-25 21:03
Centerlines are getting generated with the new vbet.

**Closed by KellyMWhitehead** 2022-10-25 21:03 UTC
Labels: enhancement, pkg:VBET
