### ISSUE TITLE
Document actual TauDEM Version in cybercaster

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#497] opened 2021-11-24 20:09 UTC
The version of tauDEM in our scripts is actually the version of the cybercaster utilization of tauDEM. We should include the actual tauDEM version (currently 5?)  for clarity.

**Comment by MattReimer** [comment] 2021-11-25 17:19
Hey @jtgilbert we do actually track that version (although there's a spelling error I see now. I'll get that fixed)

<img width="958" alt="Screen Shot 2021-11-25 at 9 16 59 AM" src="https://user-images.githubusercontent.com/1063391/143481747-b99f4fad-0617-494c-9df8-0b5019c60349.png">

We do need both versions because if I make an improvement to how we _use_ Taudem then I want that tracked.

I'm not exactly sure what's the fix here but let me know if we can provide this information in a better way

**Comment by MattReimer** [comment] 2021-11-25 17:21
Just confirmed that the metadata tag now reads `TauDEM_SoftwareVersion` so that should be fixed going forward.

**Comment by MattReimer** [comment] 2021-11-26 17:28
I'm closing this because I think it's been answered. Re-open if you disagree

**Closed by MattReimer** 2021-11-26 17:28 UTC
Labels: pkg:TauDEM
